require('dotenv').config()
require('colors')
const { scrapeUbank, formatUbank } = require('./lib/scrape-ubank.js')
const { newDate, stringHash } = require('./lib/utils.js')
const { waitForDb, saveTransactions } = require('./lib/db.js')
;(async () => {
  await waitForDb()
  const ubankTransactions = await scrapeUbank()
  // const ubankTransactions = require('./output/results.json')
  const formattedUbankTransactions = formatUbank(ubankTransactions)
  // add to db
  await saveTransactions(formattedUbankTransactions)
  console.log(`${new Date()}.dim.purple`)
  console.log('done'.yellow)
  process.exit(0)
})()
